### ISSUE TITLE
大佬能问问这个静态博客是怎么生成的吗

### ISSUE THREAD

**Issue by newamber** [Quorafind/MLkit-CN#2]
我看code里面全是md文件

**Comment by Quorafind** [comment]
利用 [docsify](https://github.com/QingWei-Li/docsify) 即可

**Comment by Quorafind** [comment]
利用 [docsify](https://github.com/QingWei-Li/docsify) 即可 @Newamber

**Comment by Newamber** [comment]
谢谢~~

**Comment by newamber** [comment]
谢谢~
