### ISSUE TITLE
感谢贡献，唐突问下人脸识别的功能必须要全程联网吗？

### ISSUE THREAD

**Issue by MrYu4** [Quorafind/MLkit-CN#5]
在不用vpn下，每当我想要调用[FIRVisionFaceDetector detectInImage:completion:]的时候都有控制台都有大几率提示网络连接失败，这个时候这个方法就没有返回的face了
[lvl=2] -[MVClearcutUploader processResponse:context:logFiles:requestTime:isBatched:error:] Error posting to Clearcut. Status Code 0, error: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=54, NSUnderlyingError=0x2806f1650 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=54, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3F3ABB12-8D7E-4651-9EA3-54EF9CC31EC4>

**Comment by Quorafind** [comment]
@MrYu4 不好意思，现在才看到，根据目前官方文档，你可以用离线加载模型，这个更加像一个在手机上可以运行的微tf框架
